apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: weatherservice
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - 'list'
  - 'watch'
- apiGroups:
  - weatherservice.vmware.com
  resources:
  - '*'
  verbs:
  - '*'
